apiVersion: v2
name: url-shortener
description: A Helm chart for deploying the url-shortener application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "69.4.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.installMonitoringStack

  - name: ingress-nginx
    version: "4.12.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled
