app:
  replicaCount: 1
  baseUrl: "http://k8s.local"
  image:
    repository: andreidon1/url-shortener
    tag: v0.0.6
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

database:
  postgres:
    initScript: |-
      CREATE TABLE urls (
          id SERIAL PRIMARY KEY,
          short_url TEXT UNIQUE NOT NULL,
          original_url TEXT NOT NULL,
          created_at TIMESTAMP DEFAULT NOW()
      );
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE urls TO app;
      GRANT USAGE, SELECT ON SEQUENCE urls_id_seq TO app;

storageClass:
  name: longhorn

nodePortService:
  enabled: true
  port: 8080
  nodePort: 30080

monitoring:
  installMonitoringStack: true
  namespace: monitoring

kube-prometheus-stack:
  namespaceOverride: monitoring
  alertmanager:
    enabled: false
  grafana:
    namespaceOverride: monitoring
    grafana.ini:
      server:
        root_url: http://k8s.local/grafana
        serve_from_sub_path: true
    ingress:
      enabled: true
      ingressClassName: nginx
      path: /grafana
      hosts:
        - "k8s.local"
  kube-state-metrics:
    namespaceOverride: monitoring
  prometheus-node-exporter:
    namespaceOverride: monitoring
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - "k8s.local"
      paths:
        - /prom
      prometheusSpec:
        externalUrl: "http://k8s.local/prom"

ingress:
  enabled: true
  controllerNamespace: ingress-nginx
  namespaces:
    - name: default
      services:
        - path: /url-shortener(/|$)(.*)
          service:
            name: url-shortener
            port: 8080
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
