{{- if .Values.monitoring.installMonitoringStack }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.monitoring.namespace }}
  labels:
    app: monitoring
  annotations:
    "helm.sh/hook": pre-install
{{- end }}

{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.ingress.controllerNamespace }}
  labels:
    app: ingress-nginx
  annotations:
    "helm.sh/hook": pre-install
{{- end }}
