apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  instances: 1
  bootstrap:
    {{- if .Values.database.postgres.restoreFromBackup.enabled }}
    recovery:
      volumeSnapshots:
        storage:
          apiGroup: ""
          kind: PersistentVolumeClaim
          name: {{ .Values.database.postgres.restoreFromBackup.PVC }}
    {{- else}}
    initdb:
      database: app
      owner: app
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: {{ .Release.Name }}-postgres-init
            key: init.sql
    {{- end }}
  storage:
    size: 5Gi
    storageClass: {{ .Values.database.postgres.storageClassName }}
    resizeInUseVolumes: False
