apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.database.postgres.image }}"
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.database.postgres.user }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-password
                  key: password
            - name: POSTGRES_DB
              value: "{{ .Values.database.postgres.dbname }}"
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/
          ports:
            - containerPort: {{ .Values.database.postgres.port }}
      volumes:
        - name: init-script
          configMap:
            name: {{ .Release.Name }}-postgres-init
