name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run unit tests
        run: |
          cd src
          go test -v ./...
      
      - name: Create short sha image tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD^)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image and run Docker compose
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/url-shortener:${{ env.IMAGE_TAG }} .
          echo -n 'TAG=${{ env.IMAGE_TAG }}' >> .env
          docker compose up -d

      #- name: Push Docker image to Docker Hub
      #  run: |
      #    docker push ${{ secrets.DOCKER_USERNAME }}/url-shortener:${{ env.IMAGE_TAG }}
